Repository BDD-CLUB/2024-2-untitled-music-back, pull requests merged in 2025-01, with the labels that each got.

#60 Feature/#45 아티스트 crud
  src/main/java/MusicPlatform/domain/artist/controller/ArtistController.java
  src/main/java/MusicPlatform/domain/artist/entity/Artist.java
  src/main/java/MusicPlatform/domain/artist/service/ArtistService.java
  src/main/java/MusicPlatform/domain/artist/service/dto/request/ArtistImageUrlDto.java
  src/main/java/MusicPlatform/global/error/ApplicationError.java
  src/main/java/MusicPlatform/global/error/ApplicationException.java
  src/main/java/MusicPlatform/global/error/ExceptionAdvice.java
Labels: 🍀 Feature

#65 Feature/#63 track 응답 정보에 업로더 정보를 추가한다
  src/main/java/MusicPlatform/domain/album/service/AlbumService.java
  src/main/java/MusicPlatform/domain/album/service/dto/response/AlbumGetResponseDto.java
  src/main/java/MusicPlatform/domain/playlist/_item/service/dto/response/PlaylistItemResponseDto.java
  src/main/java/MusicPlatform/domain/track/controller/TrackController.java
  src/main/java/MusicPlatform/domain/track/service/TrackService.java
  src/main/java/MusicPlatform/domain/track/service/dto/request/TrackRequestDto.java
  src/main/java/MusicPlatform/domain/track/service/dto/request/TrackUpdateRequestDto.java
  src/main/java/MusicPlatform/domain/track/service/dto/response/TrackGetResponseDto.java
  src/main/java/MusicPlatform/domain/track/service/dto/response/TrackResponseDto.java
Labels: 🛠️ Refactor

#69 refactor: URI 설계원칙을 따르도록 수정한다.
  src/main/java/MusicPlatform/domain/album/controller/AlbumController.java
  src/main/java/MusicPlatform/domain/artist/controller/ArtistController.java
  src/main/java/MusicPlatform/domain/playlist/controller/PlaylistController.java
  src/main/java/MusicPlatform/domain/profile/controller/ProfileController.java
  src/main/java/MusicPlatform/domain/s3/controller/S3Controller.java
  src/main/java/MusicPlatform/domain/track/controller/TrackController.java
Labels: 🛠️ Refactor

#70 Feature/#67 profile을 deprecated 시킨다
  src/main/java/MusicPlatform/domain/album/controller/AlbumController.java
  src/main/java/MusicPlatform/domain/album/entity/Album.java
  src/main/java/MusicPlatform/domain/album/repository/AlbumRepository.java
  src/main/java/MusicPlatform/domain/album/service/AlbumService.java
  src/main/java/MusicPlatform/domain/album/service/dto/response/AlbumGetResponseDto.java
  src/main/java/MusicPlatform/domain/artist/service/ArtistService.java
  src/main/java/MusicPlatform/domain/oauth2/service/CookieService.java
  src/main/java/MusicPlatform/domain/profile/controller/ProfileController.java
  src/main/java/MusicPlatform/domain/profile/entity/Profile.java
  src/main/java/MusicPlatform/domain/profile/repository/ProfileRepository.java
  src/main/java/MusicPlatform/domain/profile/service/ProfileService.java
  src/main/java/MusicPlatform/domain/track/entity/Track.java
  src/main/java/MusicPlatform/domain/track/repository/TrackRepository.java
  src/main/java/MusicPlatform/domain/track/service/dto/response/TrackGetResponseDto.java
Labels: 🛠️ Refactor

#71 Feature/#64 특정 아티스트의 플레이리스트 목록 조회 api를 구현한다
  src/main/java/MusicPlatform/domain/album/repository/AlbumRepository.java
  src/main/java/MusicPlatform/domain/album/service/AlbumService.java
  src/main/java/MusicPlatform/domain/playlist/controller/PlaylistController.java
  src/main/java/MusicPlatform/domain/playlist/repository/PlaylistRepository.java
  src/main/java/MusicPlatform/domain/playlist/service/PlaylistService.java
Labels: 🍀 Feature

#75 refactor: 불필요한 코드를 삭제한다.
  src/main/java/MusicPlatform/domain/oauth2/adapter/AuthenticationAdapter.java
  src/main/java/MusicPlatform/domain/oauth2/entity/OAuth2ProviderUser.java
  src/main/java/MusicPlatform/domain/oauth2/entity/ProviderUser.java
Labels: 🛠️ Refactor

#78 Feature/#72 하위 항목 페이징 적용 및 Resposne DTO 네이밍 규칙 변경
  src/main/java/MusicPlatform/domain/album/controller/AlbumController.java
  src/main/java/MusicPlatform/domain/album/repository/AlbumRepository.java
  src/main/java/MusicPlatform/domain/album/service/AlbumService.java
  src/main/java/MusicPlatform/domain/album/service/dto/response/AlbumBasicResponseDto.java
  src/main/java/MusicPlatform/domain/album/service/dto/response/AlbumFullResponseDto.java
  src/main/java/MusicPlatform/domain/playlist/_item/repository/PlaylistItemRepository.java
  src/main/java/MusicPlatform/domain/playlist/_item/service/PlaylistItemService.java
  src/main/java/MusicPlatform/domain/playlist/_item/service/dto/response/PlaylistItemResponseDto.java
  src/main/java/MusicPlatform/domain/playlist/controller/PlaylistController.java
  src/main/java/MusicPlatform/domain/playlist/service/PlaylistService.java
  src/main/java/MusicPlatform/domain/playlist/service/dto/response/PlaylistBasicResponseDto.java
  src/main/java/MusicPlatform/domain/playlist/service/dto/response/PlaylistFullResponseDto.java
  src/main/java/MusicPlatform/domain/track/controller/TrackController.java
  src/main/java/MusicPlatform/domain/track/repository/TrackRepository.java
  src/main/java/MusicPlatform/domain/track/service/TrackService.java
  src/main/java/MusicPlatform/domain/track/service/dto/response/TrackBasicResponseDto.java
  src/main/java/MusicPlatform/domain/track/service/dto/response/TrackFullResponseDto.java
  src/main/java/MusicPlatform/domain/track/service/dto/response/TrackGetResponseDto.java
Labels: 🛠️ Refactor

#79 feat: 파일 업로드 크기 제한 수정
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ⚙ Setting

#80 Feature/#45 아티스트 crud
  src/main/java/MusicPlatform/domain/artist/controller/ArtistController.java
  src/main/java/MusicPlatform/domain/artist/entity/Artist.java
  src/main/java/MusicPlatform/domain/artist/service/ArtistService.java
  src/main/java/MusicPlatform/domain/artist/service/dto/request/ArtistUpdateRequestDto.java
  src/main/java/MusicPlatform/global/error/ExceptionAdvice.java
Labels: 🍀 Feature

#81 Feature/#46 순환 의존을 해결한다
  src/main/java/MusicPlatform/domain/playlist/_item/service/PlaylistItemService.java
  src/main/java/MusicPlatform/domain/track/controller/TrackController.java
  src/main/java/MusicPlatform/domain/track/service/TrackService.java
Labels: 🛠️ Refactor

#82 Feature/#77 swagger bearer token 적용
  src/main/java/MusicPlatform/global/config/swagger/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🛠️ Refactor

#87 Feature/#86 track 조회시 track file url을 추가한다
  src/main/java/MusicPlatform/domain/track/entity/Track.java
  src/main/java/MusicPlatform/domain/track/service/TrackService.java
  src/main/java/MusicPlatform/domain/track/service/dto/response/TrackBasicResponseDto.java
Labels: 🍀 Feature

#89 refactor: 자식 객체가 부모 객체의 Service를 참조하도록 변경
  src/main/java/MusicPlatform/domain/album/service/AlbumService.java
  src/main/java/MusicPlatform/domain/track/service/TrackService.java
Labels: 🛠️ Refactor
